apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-hello-deployment
  labels:
    app: kube-hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kube-hello-pod
      environment: dev
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
    
  template:
    metadata:
      labels:
        app: kube-hello-pod
        environment: dev
        colour: black
    spec:
      containers:
      - name: kube-hello
        image: docker-registry.dun.fh/findmypast/kube-hello:kubet1.1
        command: ['node', 'server.js']
        ports:
          - containerPort: 3000
